config/routes.rb
InfiniteScroll::Application.routes.draw do
  resources :posts

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  self.per_page = 20

  def get_img
  	ActionController::Base.helpers.asset_path(self.thumbnail_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.paginate(:page => params[:page])
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  @@blurb_max_num_words = 32

  def pretify(str)
  	word_num = @@blurb_max_num_words - 1
  	str_words = str.split
  	str_words[0..word_num-1].join(' ')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Khen Price - Globality</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'shared/navigationbar' %>
	<%= yield %>
</body>
</html>

app/views/posts/index.html.haml
// main page
%h1 Globality Posts

// main container
.posts#masonry-container
  = render :partial => 'shared/posts', :locals => { :posts => @posts }
%nav#page-nav
  = link_to '', posts_path(:page => @posts.next_page), :class => 'load-more-posts', :remote => true if @posts.next_page

app/views/posts/index.js.haml
// handles pagination reload
$('#masonry-container').append('#{escape_javascript(render partial: "shared/posts", :locals => { :posts => @posts })}');
$('a.load-more-posts').attr('href', '#{posts_path page: @posts.next_page}');
 
- unless @posts.next_page
  $('a.load-more-posts').remove();

app/views/shared/_navigationbar.html.erb
<nav class="navbar navbar-default " role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="#" class="pull-left">
        <%= image_tag "globalityLogo.jpg", {height: 45, width:45}%>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Log In</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_posts.html.haml
// partial for post items
- posts.each do |post|
	.box.panel.panel-default#post-{:id => "post_#{post.id}"}
		%img{:src => asset_path(post.get_img)}
		%h2
			= post.title
		%p.user 
			Submitted by
			= post.title
		%p.blurb
			= pretify(post.blurb) 
			= link_to "read more...", post.details_url